<?php

require_once "../wrapper-static.php";
?>
<?= startHead() ?>
    <title>Starcraft 2 Co-op - Mutator - Trick or Treat</title>
    <link rel="canonical" href="https://starcraft2coop.com/mutators/trickortreat">
<?= startContent() ?>
    <h1>Mutator: Trick or Treat</h1>
    <p><img src="/images/mutators/trickortreat.png" alt="" /></p>
    <p>Civilians visit your Candy Bowl looking for treats, which are generated by spending minerals. If no treats are available, the civilians randomly transform into enemy units.</p>
    <table>
        <tr><th align="right">Difficulty points</th><td align="left">0</td></tr>
        <tr><th align="right">Available in custom</th><td align="left">No</td></tr>
        <tr><th align="right">Rollable in Chaos Studios</th><td align="left">No</td></tr>
    </table>
    <h2 id="detailedmutatorinformation">Detailed Mutator Information</h2>
    <p>The Candy Bowl can store a maximum of 50 candy. You have to spend 25 minerals to add 1 candy to the bowl. The candy bowl is shown below:</p>
    <img src="/images/mutatordata/trickortreatcandybowl.jpg" alt="Candy Bowl">
    <p>Civilians spawn from random enemy structures. If you destroy all enemy structures on the map, they will stop spawning. These civilians will make their way towards your Candy Bowl.  Note that all-clearing Malwarfare and Void Launch does not stop them from spawning, because Suppression Towers and Launch Bays are indestructible enemy structures.</p>
    <p>Civilians spawn every 30 seconds. The number of civilians that spawn depends on the mission time. This is shown below:</p>
    <table class="dataTable">
        <thead>
            <tr>
                <th>Mission Time</th>
                <th>Civilians Spawned</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>0:00-6:00</td>
                <td>2</td>
            </tr>
            <tr>
                <td>6:00-12:00</td>
                <td>4</td>
            </tr>
            <tr>
                <td>12:00-18:00</td>
                <td>5</td>
            </tr>
            <tr>
                <td>18:00+</td>
                <td>6</td>
            </tr>
        </tbody>
    </table>
    <p>If a Civilian walks up to the bowl which has candy, they will take 1 candy and despawn. If there is no candy in the bowl, they will transform into a unit tier as per the mission time. Tiers match that of the Transmutation mutator (see details in the Transmutation mutator details for more information). Additionally, if they cannot make their way to your bowl, they will transform after 5 minutes.</p>
    <table class="dataTable centered">
        <thead>
            <tr>
                <th>Mission Time</th>
                <th>Tier</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>0:00-2:00</td>
                <td>1</td>
            </tr>
            <tr>
                <td>2:00-4:00</td>
                <td>1-2</td>
            </tr>
            <tr>
                <td>4:00-6:00</td>
                <td>1-3</td>
            </tr>
            <tr>
                <td>6:00-7:00</td>
                <td>2-4</td>
            </tr>
            <tr>
                <td>7:00-7:30</td>
                <td>3-5</td>
            </tr>
            <tr>
                <td>7:30-8:00</td>
                <td>4-6</td>
            </tr>
            <tr>
                <td>8:00-8:30</td>
                <td>5-7</td>
            </tr>
            <tr>
                <td>8:30-9:00</td>
                <td>6-8</td>
            </tr>
            <tr>
                <td>9:00-9:30</td>
                <td>7-9</td>
            </tr>
            <tr>
                <td>9:30+</td>
                <td>8-10</td>
            </tr>
        </tbody>
    </table>
    <p>Currently, this mutator is bugged. After 10:00, the tier resets down to Tier 1.</p>
    <h2 id="commanderspecifictips">Commander-specific Tips</h2>
    <ul>
        <li>Abathur: Units spawned from Trick or Treat drop Biomass.</li>
        <li>Dehaka: Units spawned from Trick or Treat drop Essence.</li>
        <li>Mengsk: Units spawned from Trick or Treat provide Royal Guard experience.</li>
        <li>Vorazun: Time Stop does not affect Trick or Treat timings.</li>
    </ul>
    <h2 id="interactions">Mutator Interactions</h2>
    <table>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/alienincubation.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/alienincubation">Alien Incubation</a></td><td>Units spawned from Civilians spawn Broodlings when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/avenger.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/avenger">Avenger</a></td><td>Units spawned from Civilians give out and collect Avenger stacks.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/barrier.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/barrier">Barrier</a></td><td>Units spawned from Civilians get the Barrier buff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/blackdeath.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/blackdeath">Black Death</a></td><td>Units spawned from Civilians can carry Plague.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/concussiveattacks.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/concussiveattacks">Concussive Attacks</a></td><td>Units spawned from Civilians apply the Concussive Attacks debuff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/eminentdomain.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/eminentdomain">Eminent Domain</a></td><td>Civilians spawn out of structures converted by Eminent Domain.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/evasivemaneuvers.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/evasivemaneuvers">Evasive Maneuvers</a></td><td>Units spawned from Civilians get the Evasive Maneuvers buff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/fatalattraction.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/fatalattraction">Fatal Attraction</a></td><td>Units spawned from Civilians  trigger Fatal Attraction when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/fear.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/fear">Fear</a></td><td>Units spawned from Civilians can apply the Fear effect.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/fireworks.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/fireworks">Fireworks</a></td><td>Units spawned from Civilians launch Fireworks when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/hardenedwill.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/hardenedwill">Hardened Will</a></td><td>Units spawned from Civilians can cause Hardened Will to activate. Hybrids spawned from Civilians can get the Hardened Will buff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/inspiration.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/inspiration">Inspiration</a></td><td>Units spawned from Civilians can get the Inspiration buff. Hybrids spawned from Civilians can provide the Inspiration buff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/justdie.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/justdie">Just Die</a></td><td>Units spawned from Civilians respawn when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/laserdrill.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/laserdrill">Laser Drill</a></td><td>The Candy Bowl provides vision for the Laser Drill. Units spawned from Civilians provide vision for the Laser Drill.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/lifeleech.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/lifeleech">Life Leech</a></td><td>Units spawned from Civilians have Life Leech.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/longrange.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/longrange">Long Range</a></td><td>Units spawned from Civilians get the Long Range buff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/momentofsilence.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/momentofsilence">Moment of Silence</a></td><td>Hybrids spawned from Civilians trigger Moment of Silence when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/mutuallyassureddestruction.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/mutuallyassureddestruction">Mutually Assured Destruction</a></td><td>Hybrids spawned from Civilians detonate Hybrid Nukes when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/naughtylist.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/naughtylist">Naughty List</a></td><td>Units spawned from Civilians kills increase the Naughty List count.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/polarity.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/polarity">Polarity</a></td><td>Units spawned from Civilians all have Polarity applied to them.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/poweroverwhelming.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/poweroverwhelming">Power Overwhelming</a></td><td>Units spawned from Civilians  can cast abilities.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/scorchedearth.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/scorchedearth">Scorched Earth</a></td><td>Units spawned from Civilians set the ground on fire when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/selfdestruction.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/selfdestruction">Self Destruction</a></td><td>Units spawned from Civilians create an explosion when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/speedfreaks.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/speedfreaks">Speed Freaks</a></td><td>Units spawned from Civilians move faster with Speed Freaks.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/transmutation.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/transmutation">Transmutation</a></td><td>Units spawned from Civilians can Transmute.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/voidreanimators.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/voidreanimators">Void Reanimators</a></td><td>Void Reanimators can resurrect units spawned from Civilians.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/voidrifts.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/voidrifts">Void Rifts</a></td><td>Civilians do not spawn from Void Rifts.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/walkinginfested.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/walkinginfested">Walking Infested</a></td><td>Units spawned from Civilians spawn Infested when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/wemoveunseen.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/wemoveunseen">We Move Unseen</a></td><td>Units spawned from Civilians are cloaked.</td></tr>

    </table>
<script src="/scripts/nav.js"></script>
<?= endContent() ?>
