#!/bin/bash
cd "$(dirname "$0")"
npx ts-json-schema-generator --path ../data-types.ts --type CommanderList > commandersummaries.json
npx ts-json-schema-generator --path ../data-types.ts --type BrutalPlusList > brutalplus.json
