#!/bin/bash
cd "$(dirname "$0")"
bunx ts-json-schema-generator --path ../data-types.ts --type CommanderList > commandersummaries.json
bunx ts-json-schema-generator --path ../data-types.ts --type BrutalPlusList > brutalplus.json
