<?php

require_once "../../html/wrapper-static.php";
?>
<?= startHead() ?>
    <title>Starcraft 2 Co-op - Mutator - Minesweeper</title>
    <link rel="canonical" href="https://starcraft2coop.com/mutators/minesweeper">
<?= startContent() ?>
    <h1>Mutator: Minesweeper</h1>
    <p><img src="/images/mutators/minesweeper.png" alt="" /></p>
    <p>Groups of Widow Mines and Spider Mines are buried throughout the battlefield.</p>
    <table>
        <tr><th align="right">Difficulty points</th><td align="left">6</td></tr>
        <tr><th align="right">Available in custom</th><td align="left">Yes</td></tr>
        <tr><th align="right">Rollable in Chaos Studios</th><td align="left">No</td></tr>
    </table>
    <h2 id="detailedmutatorinformation">Detailed Mutator Information</h2>
    <p>At the start of the game, a total of 25 patches of Widow Mines and Spider Mines will be created. Each patch will contain 5 Widow Mines and 7 Spider Mines. The patches cannot be placed within 30 range of player start locations or within 5 range of resource patches or within 8 range of each other.</p>
    <p>Widow Mines deal direct target damage 250 (+35 vs shields) and splash damage of 80 (+40 vs shields). They have 180HP and will trigger from 5 range.</p>
    <p>Spider Mines deal a base damage of 250 within range 1.7, 50% of base damage  within range 2.25, and 25% of base damage within range 3.  They have 25HP and will trigger from 4 range.</p>
    <p>Since both, Spider Mines and Widow Mines do not attack structures, commanders with movable static defense are great at efficiently clearing mines.</p>
    <p>Mines will trigger on Aurana's transport on Malwarfare, Terrazine Harvesters on Mist Opportunities, Artifact Trucks on Cradle of Death and the Balius on Part and Parcel.</p>
    <p>Additionally, there are some other map-specific limitations:</p>
    <ul>
        <li>Chain of Ascension: Patches will not be placed within 15 range of Ji'Nara.</li>
        <li>Lock & Load: Patches will not be placed within 8 range of the Celestial Locks.</li>
    </ul>
    <p>The below image shows an example of a field generated by the mutator. Remember that you will need detection to clear the mines.</p>
    <img src="/images/mutatordata/minesweeperfield.jpg" alt="Minesweeper Field">
    <h2 id="commanderspecifictips">Commander-specific Tips</h2>
    <ul>
        <li>Kerrigan: 25 points into the Immobilization Wave mastery will allow Kerrigan to 1-shot Widow Mines.</li>
        <li>Kerrigan: Folly of Man Fury stacks can hit mines without detection.</li>
        <li>Stetmann: Getting the Hardened Egonergy Shield upgrade for Zerglings will allow them to clear mines efficiently without taking heavy losses.</li>
    </ul>
    <h2 id="interactions">Mutator Interactions</h2>
    <table>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/alienincubation.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/alienincubation">Alien Incubation</a></td><td>Mines spawn Broodlings when they are destroyed.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/avenger.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/avenger">Avenger</a></td><td>Mines can give out Avenger stacks, but cannot receive them.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/barrier.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/barrier">Barrier</a></td><td>Mines get the Barrier buff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/blackdeath.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/blackdeath">Black Death</a></td><td>Mines can carry Plague.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/concussiveattacks.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/concussiveattacks">Concussive Attacks</a></td><td>Mines apply the Concussive Attacks debuff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/evasivemaneuvers.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/evasivemaneuvers">Evasive Maneuvers</a></td><td>Mines do not get the Evasive Maneuvers buff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/fatalattraction.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/fatalattraction">Fatal Attraction</a></td><td>Mines trigger Fatal Attraction when they are destroyed.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/fear.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/fear">Fear</a></td><td>Mines can apply the Fear effect.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/fireworks.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/fireworks">Fireworks</a></td><td>Mines do not launch Fireworks when they are destroyed.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/giftexchange.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/giftexchange">Gift Exchange</a></td><td>Mines can capture gifts.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/hardenedwill.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/hardenedwill">Hardened Will</a></td><td>Mines cause Hardened Will to activate.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/justdie.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/justdie">Just Die</a></td><td>Mines respawn when they are destroyed.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/laserdrill.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/laserdrill">Laser Drill</a></td><td>Mines provide vision for the Laser Drill.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/longrange.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/longrange">Long Range</a></td><td>Mines do not get the Long Range buff.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/naughtylist.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/naughtylist">Naughty List</a></td><td>Mine kills increase the Naughty List count.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/polarity.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/polarity">Polarity</a></td><td>Widow Mines and Spider Mines all have Polarity applied to them.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/poweroverwhelming.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/poweroverwhelming">Power Overwhelming</a></td><td>Widow mines can cast abilities. Spider mines cannot cast abilities.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/scorchedearth.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/scorchedearth">Scorched Earth</a></td><td>Mines set the ground on fire when they die.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/selfdestruction.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/selfdestruction">Self Destruction</a></td><td>Mines set the ground on fire when they are destroyed.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/speedfreaks.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/speedfreaks">Speed Freaks</a></td><td>Spider mines do not move faster with Speed Freaks.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/transmutation.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/transmutation">Transmutation</a></td><td>Widow Mines Transmute after killing a unit.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/voidreanimators.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/voidreanimators">Void Reanimators</a></td><td>Void Reanimators resurrect Widow Mines but not Spider Mines. Widow Mines will move towards player bases after resurrection.</td></tr>
        <tr><td style="white-space:nowrap"><img src="/images/mutators/walkinginfested.png" height="25" width="25" style="vertical-align:middle"> <a href="/mutators/walkinginfested">Walking Infested</a></td><td>Mines spawned Infested when they are destroyed.</td></tr>

    </table>
<script src="/scripts/nav.js"></script>
<?= endContent() ?>
