#!/usr/bin/env bun
// @ts-check
export {};

/** @type {import('./data-types.ts').BrutalPlus[]} */
const brutalPluses = await Bun.file('data/brutalplus.json').json();
/** @type {import('./data-types.ts').Commander[]} */
const commanders = await Bun.file('data/commandersummaries.json').json();

Bun.write('public_html/data/brutalplus.json', JSON.stringify(brutalPluses, null, 4) + '\n');
for (const brutalPlus of brutalPluses) {
	Bun.write(`public_html/data/brutalplus/${brutalPlus.difficulty}.json`, JSON.stringify(brutalPlus, null, 4) + '\n');
}
Bun.write('public_html/data/commandersummaries.json', JSON.stringify(commanders, null, 4) + '\n');
for (const commander of commanders) {
	Bun.write(`public_html/data/commandersummaries/${commander.commander}.json`, JSON.stringify(commander, null, 4) + '\n');
}
