#!/usr/bin/env bun
// @ts-check
export {};

/** @type {import('./data-types.ts').BrutalPlus[]} */
const brutalPluses = await Bun.file('data/brutalplus.json').json();
/** @type {import('./data-types.ts').Commander[]} */
const commanders = await Bun.file('data/commandersummaries.json').json();

console.log(`Writing brutalplus.json`);	
Bun.write('public_html/data/brutalplus.json', JSON.stringify(brutalPluses, null, 4) + '\n');
for (const brutalPlus of brutalPluses) {
	console.log(`Writing brutalplus/${brutalPlus.difficulty}.json`);
	Bun.write(`public_html/data/brutalplus/${brutalPlus.difficulty}.json`, JSON.stringify(brutalPlus, null, 4) + '\n');
}
console.log(`Writing commandersummaries.json`);
Bun.write('public_html/data/commandersummaries.json', JSON.stringify(commanders, null, 4) + '\n');
for (const commander of commanders) {
	console.log(`Writing commandersummaries/${commander.commander}.json`);
	Bun.write(`public_html/data/commandersummaries/${commander.commander}.json`, JSON.stringify(commander, null, 4) + '\n');
}
console.log(`Done`);
