#!/usr/bin/env bun
// @ts-check
import Ajv from 'ajv';

/** @type {import('./data-types.ts').BrutalPlus[]} */
const brutalPluses = await Bun.file('data/brutalplus.json').json();
/** @type {import('./data-types.ts').Commander[]} */
const commanders = await Bun.file('data/commandersummaries.json').json();

/** @type {import('./data-types.ts').BrutalPlus[]} */
const brutalPlusesSchema   = await Bun.file('data/schemas/brutalplus.json').json();
/** @type {import('./data-types.ts').Commander[]} */
const commandersSchema = await Bun.file('data/schemas/commandersummaries.json').json();

const ajv = new Ajv();

const validateBrutalPluses = ajv.compile(brutalPlusesSchema);
if (!validateBrutalPluses(brutalPluses)) {
    console.error('BrutalPluses validation failed');
    console.error(validateBrutalPluses.errors);
    process.exit(1);
}

const validateCommanders = ajv.compile(commandersSchema);
if (!validateCommanders(commanders)) {
    console.error('Commanders validation failed');
    console.error(validateCommanders.errors);
    process.exit(1);
}

console.log('All validations passed');
